apiVersion: apps/v1
kind: Deployment
metadata:
  name: neovis-flask
  namespace: graphdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neovis-flask
  template:
    metadata:
      labels:
        app: neovis-flask
    spec:
      containers:
        - name: neo4j
          image: 'aguinaldoabbj/neovis-flask'
---
apiVersion: v1
kind: Service
metadata:
  name: neovis-flask-service
  namespace: graphdb
  labels:
    name: neovis-flask-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: neovis-flask
  type: ClusterIP